sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 17J5U2iK53Y1hvcwEzLtH2/uRYeWnZAVsluuBF9PwyHMXURR5GJON8FQLbEVc1MxfffMJ4jxpkOZQcnoC5xtNreP7MoKy0CLMUaxBn0HSFAkghG73ELAZ5rj1ajQVJiEmcMjAVmPld4UeAUaRUxWEdIOwzNqSPxH/YCyTqXAL09mhi4D+G4158BBR6VhF7pYjGX/lRG1plCbm90jtVgtd7m6eDf8W41GsKXcXRNgUXWysMjufxpK6EfyQIPNR+ICZuz/tQPGpBskZ0fNDGTjwlOWAiO9FIbtu1yzH25a4tDPoy+VEqzf0Z6D2C57oKj6fjZc60IhbfgXCr0gfZqGDwCF3qhtjT7EZ50/eJwaP2WNe/UKJH8ObRaGC/Db1EbRHRbWP5JXnJp66npJYeRfvG52gI3z4tb47Qr3UYkK6MH3J8C1FrmEi/METGAgGD5b67hGeSNiBxVaMnvcjahDO69DVa5IyMxOBKa2tT2yq6HT4GG+ng94jv0v/UZ9RxkVyazLTYzK6FVxY0DMmFvzEi87tJj8iVakBNGdb1x9sScByArMGt+8meNbrml3wPIJ+2Xy7njBhyz/4E9Xrb5M0MA2Uhm07TWJTUf9H/+D6iFkMw4QcA1V71H5cE8jvE0BZkw8xkotjaaugNN7Zu0EDUZMtfk4/P5DOToNS/SkQSk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Memoirs-of-Jacques-Casanova-de-Seingalt-1725-1798.-Volume-12--Return-to-Paris_2962
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy